name: 자막 만들기

on:
  push:
    branches: [ main/master ]
  pull_request:
    branches: [ main/master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: |
          python EvergreenSlideMaker/exe.py

          
      - name: commit files
        run: |
          git config --local user.email "the_savvy@naver.com"
          git config --local user.name "whiz-savvy"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: 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
          branch: main 
